remote_theme: pmarsceill/just-the-docs

search_enabled: true

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

logo: "/assets/images/logo.png"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

nav_external_links:
  - title: Fronter Kea
    url: https://kea-fronter.itslearning.com